START C:\01_in_member.sql
START C:\02_in_publisher.sql
START C:\03_in_book.sql
START C:\04_in_author.sql
START C:\05_in_category.sql
START C:\06_in_book_category.sql
START C:\07_in_book_author.sql
START C:\08_in_rating.sql
START C:\09_in_loan.sql
START C:\10_in_return.sql
START C:\11_in_payment.sql
START C:\12_in_reservation.sql
START C:\13_in_book_reservation.sql